
export const ADD_CONTENTS = 'ADD_CONTENTS';
export const CONTENTS_LOADING = 'CONTENTS_LOADING';
export const CONTENTS_FAILED = 'CONTENTS_FAILED';
export const ADD_CONFIGS = 'ADD_CONFIGS';
export const CONFIGS_LOADING = 'CONFIGS_LOADING';
export const CONFIGS_FAILED = 'CONFIGS_FAILED';
export const ADD_CATEGORIES = 'ADD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';
export const CATEGORIES_FAILED = 'CATEGORIES_FAILED';
export const ADD_NOTES = 'ADD_NOTES';
export const NOTES_LOADING = 'NOTES_LOADING';
export const NOTES_FAILED = 'NOTES_FAILED';
export const ADD_REFS = 'ADD_REFS';
export const REFS_LOADING = 'REFS_LOADING';
export const REFS_FAILED = 'REFS_FAILED';
export const ADD_NOTE = 'ADD_NOTE';
export const ADD_REF = 'ADD_REF';


export const ADD_LEADERS = 'ADD_LEADERS';
export const ADD_FEEDBACK = 'ADD_FEEDBACK';